### ISSUE TITLE
ttf-parser does not build on rust 1.89

### ISSUE THREAD

**Issue by Kl4rry** [harfbuzz/ttf-parser#196]
`rustc 1.89.0 (29483883e 2025-08-04)`
When I build ttf parser on rust 1.89 I get:
```
    Checking ttf-parser v0.25.1
error[E0425]: cannot find function `parse_char_string` in this scope
   --> /home/axel/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ttf-parser-0.25.1/src/tables/cff/cff1.rs:960:9
    |
417 | / fn _parse_char_string(
418 | |     ctx: &mut CharStringParserContext,
419 | |     char_string: &[u8],
420 | |     depth: u8,
...   |
689 | |     Ok(())
690 | | }
    | |_- similarly named function `_parse_char_string` defined here
...
960 |           parse_char_string(data, self, glyph_id, false, builder).map(|v| v.0)
    |           ^^^^^^^^^^^^^^^^^
    |
note: function `crate::cff2::parse_char_string` exists but is inaccessible
   --> /home/axel/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ttf-parser-0.25.1/src/tables/cff/cff2.rs:232:1
    |
232 | / fn parse_char_string(
233 | |     data: &[u8],
234 | |     metadata: &Table,
235 | |     coordinates: &[NormalizedCoordinate],
...   |
279 | |     bbox.to_rect().ok_or(CFFError::BboxOverflow)
280 | | }
    | |_^ not accessible
help: the leading underscore in `_parse_char_string` marks it as unused, consider renaming it to `parse_char_string`
    |
417 - fn _parse_char_string(
417 + fn parse_char_string(
    |

error[E0425]: cannot find function `parse_char_string` in this scope
   --> /home/axel/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ttf-parser-0.25.1/src/tables/cff/cff1.rs:993:21
    |
417 | / fn _parse_char_string(
418 | |     ctx: &mut CharStringParserContext,
419 | |     char_string: &[u8],
420 | |     depth: u8,
...   |
689 | |     Ok(())
690 | | }
    | |_- similarly named function `_parse_char_string` defined here
...
993 |                       parse_char_string(data, self, glyph_id, true, &mut DummyOutline).ok()?;
    |                       ^^^^^^^^^^^^^^^^^
    |
note: function `crate::cff2::parse_char_string` exists but is inaccessible
   --> /home/axel/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ttf-parser-0.25.1/src/tables/cff/cff2.rs:232:1
    |
232 | / fn parse_char_string(
233 | |     data: &[u8],
234 | |     metadata: &Table,
235 | |     coordinates: &[NormalizedCoordinate],
...   |
279 | |     bbox.to_rect().ok_or(CFFError::BboxOverflow)
280 | | }
    | |_^ not accessible
help: the leading underscore in `_parse_char_string` marks it as unused, consider renaming it to `parse_char_string`
    |
417 - fn _parse_char_string(
417 + fn parse_char_string(
    |

For more information about this error, try `rustc --explain E0425`.
error: could not compile `ttf-parser` (lib) due to 2 previous errors
```

**Comment by Kl4rry** [comment]
That is odd
